# Generated by Django 3.2.12 on 2022-03-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(max_length=250, upload_to='users/', verbose_name='Аватарка'),
        ),
    ]
